name: Reusable Workflow to Run Tests

on:
  workflow_call:
    inputs:
      tags-of-tests-to-include:
        required: true
        type: string
      tags-of-tests-to-exclude:
        required: false
        type: string
        default: "flaky, failing"
      test-environment:
        required: false
        type: string
        default: "STAGING"
      run-name:
        required: false
        type: string
        default: "CI"

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Unlock secrets
        uses: sliteteam/github-action-git-crypt-unlock@1.2.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}

      - name: Run tests with Maven
        id: test
        run: |
          mvn \
          -DexcludedGroups="${{ inputs.tags-of-tests-to-exclude }}" \
          -Dgroups="${{ inputs.tags-of-tests-to-include }}" \
          -DTEST_ENV="${{ inputs.test-environment }}" \
          -DTRIGGERED_BY="${{ github.event_name }}" \
          -DRUN_NAME="${{ inputs.run-name }}" \
          clean test
        continue-on-error: true

      - name: Collect test results
        id: collect-results
        run: |
          mkdir -p test-results
          find . -name "TEST-*.xml" -type f -exec cp {} test-results/ \;

      - name: Compile ParseTestResults Java Program
        run: |
          javac -d . ParseTestResults.java

      - name: Run ParseTestResults
        run: |
          java ParseTestResults test-results/*.xml

      - name: Read Test Results Summary
        id: get_summary
        run: |
          summary=$(cat test_results_summary.txt)
          echo "::set-output name=summary::$summary"
        shell: bash

      - name: Send email notification
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "GitHub Actions: Test Results"
          body: |
            Hello,

            Please find the attached test results from the latest GitHub Actions run.

            Summary:
            ${{ steps.get_summary.outputs.summary }}

            For a detailed view, please refer to the attached report.

            Best regards,
            Your Automation Team
          to: ${{ secrets.TO_EMAIL }}
          from: ${{ secrets.SMTP_USERNAME }}
          attachments: |
            test-results/*.xml
