name: Reusable Workflow to Run Tests

on:
  workflow_call:
    inputs:
      tags-of-tests-to-include:
        required: true
        type: string
      tags-of-tests-to-exclude:
        required: false
        type: string
        default: "flaky, failing"
      test-environment:
        required: false
        type: string
        default: "MAIL_NOTIFICATION"
      run-name:
        required: false
        type: string
        default: "CI"

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Start Selenoid server
        uses: n-ton4/selenoid-github-action@master
        id: start-selenoid
        continue-on-error: false
        with:
          version: 1.10.1
          args: -limit 5
          browsers: chrome
          last-versions: 1

      - name: Check Selenoid has been started
        run: curl http://localhost:4444/status

      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Test with Maven
        id: run-tests
        run: |
          mvn clean -B package --file pom.xml \
            -DexcludedGroups="${{ inputs.tags-of-tests-to-exclude }}" \
            -Dgroups="${{ inputs.tags-of-tests-to-include }}" \
            -DTEST_ENV="${{ inputs.test-environment }}" \
            -DRUN_NAME="${{ inputs.run-name }}" \
            -Dselenide.remote=http://localhost:4444/wd/hub \
            -DTRIGGERED_BY=${{ github.event_name }}

      - name: Retrieve Selenide Reports
        id: retrieve-reports
        run: |
          report_dir="path/to/selenoid/reports"  # Update this to your actual reports folder
          # Assuming Selenide generates a summary.json file
          test_results=$(cat $report_dir/summary.json)
          total_tests=$(echo "$test_results" | jq '.total')
          total_failures=$(echo "$test_results" | jq '.failures')
          total_errors=$(echo "$test_results" | jq '.errors')
          total_skipped=$(echo "$test_results" | jq '.skipped')
          echo "TOTAL_TESTS=$total_tests" >> $GITHUB_ENV
          echo "TOTAL_FAILURES=$total_failures" >> $GITHUB_ENV
          echo "TOTAL_ERRORS=$total_errors" >> $GITHUB_ENV
          echo "TOTAL_SKIPPED=$total_skipped" >> $GITHUB_ENV

      - name: Output test results for debug
        run: |
          echo "Tests run: ${{ env.TOTAL_TESTS }}"
          echo "Failures: ${{ env.TOTAL_FAILURES }}"
          echo "Errors: ${{ env.TOTAL_ERRORS }}"
          echo "Skipped: ${{ env.TOTAL_SKIPPED }}"

      - name: Send Email Notification
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          from: Luke Skywalker <${{ secrets.SMTP_USERNAME }}>
          to: ${{ secrets.TO_EMAIL }}
          subject: "GitHub Actions Notification"
          body: |
            Dear all,

            Your scheduled workflow ran successfully!

            Summary:
            Tests run: ${{ env.TOTAL_TESTS }}
            Failures: ${{ env.TOTAL_FAILURES }}
            Errors: ${{ env.TOTAL_ERRORS }}
            Skipped: ${{ env.TOTAL_SKIPPED }}

            Regards,
            Your Automation System
