name: reusable-workflow-to-run-tests

on:
  workflow_call:
    inputs:
      tags-of-tests-to-include:
        required: true
        type: string
      tags-of-tests-to-exclude:
        required: false
        type: string
        default: "flaky, failing"
      test-environment:
        required: false
        type: string
        default: "STAGING"
      run-name:
        required: false
        type: string
        default: "CI"

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Unlock secrets
        uses: sliteteam/github-action-git-crypt-unlock@1.2.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}

      - name: Test with Maven
        id: test
        run: |
          mvn \
          -DexcludedGroups="${{ inputs.tags-of-tests-to-exclude }}" \
          -Dgroups="${{ inputs.tags-of-tests-to-include }}" \
          -DTEST_ENV="${{ inputs.test-environment }}" \
          -DTRIGGERED_BY="${{ github.event_name }}" \
          -DRUN_NAME="${{ inputs.run-name }}" \
          clean -B package --file pom.xml | tee test-results.txt

      - name: Parse test results
        id: parse-results
        run: |
          mkdir -p surefire-reports
          cp target/surefire-reports/*.xml surefire-reports/

          # Install xmlstarlet
          sudo apt-get update
          sudo apt-get install -y xmlstarlet

          # Extract test results using xmlstarlet
          xmlstarlet sel -T -t -m "//testcase" -v "concat(@classname, '.', @name, ', Status: ', if(failure) then 'failed' else if(error) then 'error' else if(skipped) then 'skipped' else 'passed', ', Time: ', @time)" -n surefire-reports/*.xml > test-summary.txt

      - name: Read test summary
        id: read-summary
        run: |
          test_summary=$(cat test-summary.txt)
          echo "test_summary<<EOF" >> $GITHUB_ENV
          echo "$test_summary" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Send Email Notification
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "GitHub Actions: Test Results"
          body: |
            The test run has completed.
            - Environment: ${{ inputs.test-environment }}
            - Included Tags: ${{ inputs.tags-of-tests-to-include }}
            - Excluded Tags: ${{ inputs.tags-of-tests-to-exclude }}
            - Run Name: ${{ inputs.run-name }}
            - Triggered By: ${{ github.event_name }}
            - Job Status: ${{ job.status }}
            - Test Results:
            ${{ env.test_summary }}
          to: ${{ secrets.TO_EMAIL }}
          from: ${{ secrets.SMTP_USERNAME }}
