name: Trigger Tests on a Schedule

on:
  schedule:
    - cron: '41 8 1 * *'   # At 08:41 on the 1st day of every month.
    - cron: '51 8 * * MON' # At 08:51 UTC every Monday.
  workflow_dispatch:     # This allows the workflow to be manually triggered

jobs:
  trigger-tests-on-schedule:
    runs-on: ubuntu-latest
    name: Trigger Tests on Schedule
    steps:
      - name: Run Reusable Workflow to Run Tests
        uses: ./.github/workflows/reusable-workflow-to-run-tests.yml
        with:
          tags-of-tests-to-include: ""   # -Dgroups="" means execute all test cases
          tags-of-tests-to-exclude: ""   # -DexcludedGroups="" means don't exclude any test case
          test-environment: "MAIL_NOTIFICATION"  # Optional, default value used
          run-name: "CI"   # Optional, default value used
          secrets: inherit  # Ensure secrets are passed to the reusable workflow
        env:
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
