name: Trigger Tests on a Schedule

on:
  schedule:
    - cron: '41 8 1 * *'  # At 08:41 on the 1st day of every month.
    - cron: '51 8 * * Mon'  # At 08:51 UTC every Monday.
  workflow_dispatch:  # This allows the workflow to be manually triggered

jobs:
  run-tests-and-send-notification:
    name: Run Tests on Schedule and Send Notification
    runs-on: ubuntu-latest

    steps:
      - name: Run Reusable Workflow to Run Tests
        uses: ./.github/workflows/reusable-workflow-to-run-tests.yml
        with:
          tags-of-tests-to-include: ""  # -Dgroups="" means execute all test cases
          tags-of-tests-to-exclude: ""  # -DexcludedGroups="" means don't exclude any test case
          test-environment: "BMT_PLUS"  # Pass test environment
          run-name: "CI"  # Pass run name
        secrets: inherit  # Ensure secrets are passed to the reusable workflow

      - name: Send Notification
        if: always()  # Ensure this job runs regardless of the previous job's outcome
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          from: ${{ secrets.EMAIL_USERNAME }}  # Use the same value as the username for the 'from' field
          subject: "GitHub Actions Notification"
          body: |
            Dear all,

            Your scheduled workflow ran successfully!

            Test Results:
            ${{ env.TEST_CASES }}

            Summary:
            Tests run: ${{ env.TOTAL_TESTS }}
            Failures: ${{ env.TOTAL_FAILURES }}
            Errors: ${{ env.TOTAL_ERRORS }}
            Skipped: ${{ env.TOTAL_SKIPPED }}

            Regards,
            Your Automation System
          to: ${{ secrets.TO_EMAIL }}